# Dockerfile
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-eng \
    poppler-utils \
    libgl1 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy required files
COPY ./backend/requirements.txt .
COPY ./backend /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set Tesseract path
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata

# Expose port
EXPOSE 8000

# Start command
CMD ["gunicorn", "--worker-tmp-dir", "/tmp", "--timeout", "120", "--workers", "2", "wsgi:app", "--bind", "0.0.0.0:8000"]